name: TEST deployment
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{github.ref}}

    steps:
      - name: github ref_name
        run: echo ${{github.ref}}
      
      - name: github ref_name por si acaso
        run: echo "${{ github.ref }}"

      - name: Log text variable
        run: echo ${{ vars.TEXT }}

      - name: Log text variable por si acaso
        run: echo "${{ vars.TEXT }}"